name: dartbowling
description: A simple command-line bowling application.
version: 1.0.0
homepage: https://github.com/czenzel/dart-bowling

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
