name: dartbowling
description: An easy library to help aid in tracking bowling game scores with Flutter and Dart.
version: 1.0.3
homepage: https://github.com/czenzel/dart-bowling

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
